# Generated by Django 4.0.4 on 2022-04-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DB', 'DEBIT'), ('CD', 'CREDIT_CARD')], default='DB', max_length=2)),
                ('is_paid', models.BooleanField()),
            ],
        ),
    ]
