# Generated by Django 4.0.4 on 2022-04-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(verbose_name='date of expiration')),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
        ),
    ]
